CREATE DATABASE  IF NOT EXISTS `sjjh`;
USE `sjjh`;
DROP TABLE IF EXISTS `queue_bank`;
CREATE TABLE `queue_bank` (
  `UUID` varchar(255) NOT NULL,
  `INTERFACE_ID` varchar(255) DEFAULT NULL,
  `REQUEST_ID` varchar(255) DEFAULT NULL,
  `RESPONSE_ID` varchar(255) DEFAULT NULL,
  `QUERY_ID` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `REQUESTER` varchar(255) DEFAULT NULL,
  `REPLIER` varchar(255) DEFAULT NULL,
  `RECEIVE_REQUEST_TIME` datetime DEFAULT NULL,
  `SEND_REQUEST_TIME` datetime DEFAULT NULL,
  `RECEIVE_RESPONSE_TIME` datetime DEFAULT NULL,
  `SEND_RESPONSE_TIME` datetime DEFAULT NULL,
  `DECODED_PARAM` text DEFAULT NULL,
  `DECODED_RESULT` text DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `UUID` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;